os: osx #This Is Because https://github.com/chenzhutian/hexo-all-minifier/issues/51
language: node_js
node_js:
- 8.12.0
branches:
  only:
  - master

install: npm install

before_script:
- git config --global user.name "Oscar Beaumont"
- git config --global user.email "oscartbeaumont@gmail.com"
#- sed -i "s/__GITHUB_TOKEN__/${__GITHUB_TOKEN__}/" _config.yml # Linux
- sed -i '' "s/__GITHUB_TOKEN__/${__GITHUB_TOKEN__}/g" _config.yml #MacOS

script: npm run build
