# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Oscar Beaumont
subtitle:
description: Hello There, My name is Oscar Beaumont, I am a high school student, developer and a tech enthusiast. This is my personal website and blog. Click Here to read more!
keywords: Technology Linux Servers Programming Robotics Developer Oscar Beaumont otbeaumont oscartbeaumont
author: Oscar Beaumont
language: en
timezone: Australia/Perth

# URL
url: https://otbeaumont.me
root: /
permalink: blog/:title/
permalink_defaults:

exclude:
  - .DS_Store

# Directory
source_dir: source
public_dir: dist
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang

# Writing
new_post_name: :title.md
default_layout: draft
titlecase: false
external_link: true
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: "/blog"
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: apollon

menu: #Themes Menu
  Home: /
  Blog: /blog
  Projects: /projects
  Contact: /contact
  GitHub: https://github.com/oscartbeaumont

social_bar: #Accounts For Social Bar
  github: oscartbeaumont
  spotify: oscartbeaumont
  email: oscartbeaumont@gmail.com
  rss: https://otbeaumont.me/atom.xml

startyear: 2018 # Copyright Infomation

# Hexo SEO Sitemap
sitemap:
  path: sitemap.xml

# Hexo Auto Nofollow Attribute
nofollow:
  enable: true
  exclude:
    - github.com
    - open.spotify.com
    - gmail.com

# Minify Everthing
all_minifier: true

# Include redirects file
include:
  - _redirects

# Prevent The CMS Interface Being Modified By Hexo
skip_render:
  - "*admin/*"
